version: '3'
services:
  api:
    build: ./src/api
    ports:
     - "5000:5000"
    volumes:
     - ./src/api:/root
  static:
    build: ./src/static
    ports:
      - "3000:3000"
    volumes:
      - ./src/static:/root