version: '3'
services:
  api:
    build: ./src/api
    ports:
     - "5000:5000"
    volumes:
     - ./src/api:/root

  static:
    build: ./src/static
    ports:
      - "3000:3000"
    volumes:
      - ./src/static:/root

  messaging:
    build: ./src/messaging
    env_file:
      - src/messaging/secrets.env
    environment:
      - TWILIO_PHONE=+12169302380
      - API_URL=http://whoskickin_api_1:5000/api
      - RECIPIENT_PHONE_NUMBERS=+12168322276
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
    volumes:
      - ./src/messaging:/root
